volumes:
  mongo-data:
  redis-data:

services:
  mongo:
    volumes:
      - mongo-data:	/mnt/.ix-apps/docker/volumes/data/_data/data/db

  redis:
    volumes:
      - redis-data:	/mnt/.ix-apps/docker/volumes/data/_data/data
